### ISSUE TITLE
SIGPIPE causes exit only when using signal-exit

### ISSUE THREAD

**Issue by parshap** [tapjs/signal-exit#19]
Here are my observations:

1. With the following code running as a server, I can crash the process by loading `localhost:8000` in my browser (Chrome 47) and spamming refresh at a rate of about 5 times per second, giving the page a chance to begin rendering but not finish loading. The server prints `process exiting null SIGPIPE` before exiting with code `141`.

  ```js
  var onExit = require('signal-exit')
  onExit(function (code, signal) {
    console.log('process exiting', code, signal)
  })

  var fs = require("fs");
  require("http").createServer(function(req, res) {
    fs.createReadStream("/usr/share/dict/words").pipe(res);
  }).listen(8000);
  ```

  *Note:* You may have to fix the path to your dictionary file (or use another sufficiently large file).

2. If I remove the the call to `onExit()`, the server will no longer crash when spamming refresh from the browser.

3. If I add my own SIGPIPE handler, I can see that the process is definitely receiving the signal when spamming refresh from the browser.

  ```js
  process.on("SIGPIPE", function() {
    console.log("SIGPIPE");
  });
  ```

I'm not sure exactly what's going on and whether it's a problem with signal-exit, my code, or node. The node docs mention that ["`SIGPIPE` is ignored"](https://github.com/nodejs/node/blame/44aba1ab1c2656caf8f0f03a2f47b4c4b35aa4a2/doc/api/process.markdown#L243), but I'm not sure what that means exactly. I'm using `signal-exit@2.1.2` and node `v4.2.4` on Ubuntu 14.04 with kernel `3.13.0-32-generic`.

**Comment by parshap** [comment]
I think I have a good understanding of what's going on now.

1. Normally, if an http request is aborted by the other side, you can still write to the (closed) response and not get an error.

2. There appears to be a bug in node, where *sometimes*, by writing to a closed response, your process will receive a SIGPIPE signal. I can only get this to happen by aborting requests using a real browser (see instructions in OP above). Normally this doesn't cause any issues because node, by default, does not exit when receiving SIGPIPE.

3. signal-exit [handles SIGPIPE](https://github.com/tapjs/signal-exit/blob/bdb83f16a9872db485371e258d6c3dc73c621710/signals.js#L26) and [causes node to exit](https://github.com/tapjs/signal-exit/blob/bdb83f16a9872db485371e258d6c3dc73c621710/index.js#L86). Why would sending SIGPIPE to our own process cause it to exit when SIGPIPE previously did not cause exit? I don't know why node behaves like this, but if you add a SIGPIPE handler then remove the handler, SIGPIPE will begin terminating the process. See:

  ```
  $ node -e 'process.kill(process.pid, "SIGPIPE")'
  $ echo $?
  0
  ```

  ```
  $ node -e 'function o(){}; process.on("SIGPIPE", o); process.removeListener("SIGPIPE", o); process.kill(process.pid, "SIGPIPE")'
  $ echo $?
  141
  ```
  
I think the following actions need to be taken:

1. signal-exit should stop listening for SIGPIPE. It is not an exit-causing signal and thus should not be handled by this module. I can send a PR to remove SIGPIPE from signals.js and attempt a test.

2. Node should have consistent behavior when writing to a closed response and not *sometimes* cause SIGPIPE. I can open an issue on the node repo about this.

3. Node should handle SIGPIPE consistently and not change behavior when a handler is added then removed. I can open an issue on the node repo about this.

Let me know if this sounds right before I take further action.

**Comment by bcoe** [comment]
@parshap this should now be landed 🎉
