### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by thisconnect** [tapjs/signal-exit#44]
Hi
I'm getting to following warning:

```
(node:42081) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at EventEmitter.addListener (events.js:275:10)
    at module.exports (node_modules/signal-exit/index.js:41:11)
    at module.exports.err (node_modules/exec-buffer/node_modules/execa/index.js:146:23)
    at fsP.writeFile.then (node_modules/exec-buffer/index.js:35:15)
```

Related:
- https://github.com/sindresorhus/execa/issues/61
- https://github.com/imagemin/imagemin/issues/211

Please correct me if I am wrong:
signal-exit has one global eventemitter instance (https://github.com/tapjs/signal-exit/blob/master/index.js#L13)
each time signal-exit is used somewhere it adds a listener `.on()` here https://github.com/tapjs/signal-exit/blob/master/index.js#L41

At the 11th time signal-exit is used Node's https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners starts complaining.

**Comment by monkindey** [comment]
+1

**Comment by isaacs** [comment]
Wow, you have 11 signal-exit handlers?

That seems... unusual.  What are you doing to end up there?  My gut sense would be that the warning is a valid complaint about your program.

It'd be possible for signal-exit to manage its own list of handlers, but I'd want to understand the use case better first.

**Comment by evilebottnawi** [comment]
@isaacs i am using offical imagemin with 4 plugins

**Comment by isaacs** [comment]
Root cause: https://github.com/sindresorhus/execa/issues/61#issuecomment-259746099

Looks like signal-exit is working as designed.  The warning is a legitimate complaint about execa not cleaning up unneeded handlers.

If I'm misunderstanding the situation, I'm happy to reevaluate.  The changes required to signal-exit to support having an unlimited number of handlers would be relatively straightforward.

**Comment by thisconnect** [comment]
You are probably right. I have a repo that tests various images with imagemin. I cloud batch the jobs. 

Another usecase is described here https://github.com/sindresorhus/execa/issues/61

I'd be happy if you mention the 10 instance limit in the readme. Or make a configuration to setmaxeventlisteners or smth like that
