### ISSUE TITLE
async onExit handler

### ISSUE THREAD

**Issue by rgranger** [tapjs/signal-exit#46]
Async methods inside the onExit callback are never called.

example :

    onExit(() => {
      console.log('onExit')
      setTimeout(() => {
        console.log('async onExit')
      }, 0)
    })

Result : 

'onExit' is logged whereas 'async onExit' is not.

Is it purposeful ?

When i tried :

    process.on('SIGINT', () => {
      console.log('onExit')
      setTimeout(() => {
        console.log('async onExit')
      }, 0)
    })

Both messages were correctly logged.

This is useful for me because I need to remove temporary directories when process exit on an unexpected way.

**Comment by bcoe** [comment]
@rgranger this is by design; Node allows a handler to be registered before exiting, but any operations that take place in this handler must be synchronous.

**Comment by rgranger** [comment]
Ok, but then, why does it work when I use an async function in the raw process.on('SIGINT')

**Comment by parshap** [comment]
I believe when you handle a signal using `process.on`, Node will no longer perform the default behavior of exiting. Your app will continue as normal, but probably since you are just performing one or async task and then there is nothing left your app quits as expected. This module doesn't prevent the default behavior of aborting, just gives you a hook to perform some synchronous task before the exit happens.

**Comment by isaacs** [comment]
Yes, if the signal is handled, then you're choosing not to exit as a result of that signal.

```
$ cat cmd-c-nope.js
const msgs = [ 'nope', 'try again', 'better luck next time']
process.on('SIGINT', () => console.log(msgs[Math.floor(Math.random() * msgs.length)]))
setInterval(() => {}, 1000000)

$ node cmd-c-nope.js
^Cnope
^Cnope
^Cnope
^Ctry again
^Cnope
^Cnope
^Ctry again
^Ctry again
^Cbetter luck next time
^Cnope
^Ctry again
^Z
[1]+  Stopped                 node cmd-c-nope.js

$ kill -9 %1

[1]+  Stopped                 node cmd-c-nope.js

$
[1]+  Killed: 9               node cmd-c-nope.js

$
```
