### ISSUE TITLE
`kill ENOSYS` error coming from this module on Windows

### ISSUE THREAD

**Issue by TooTallNate** [tapjs/signal-exit#54]
Via our error reporting mechanism in Now CLI, we get periodic error coming from this module when running on Windows with the error message `kill ENOSYS`. The error comes from this line of code:

https://github.com/tapjs/signal-exit/blob/395ccc8cf3cc119dc98a0d38940dbfaa590af0cd/index.js#L95

It's not clear to me from the error reporting which `sig` is causing the error here, but possibly it's `SIGHUP` since it's [listed in `signals.js` for all operating systems](https://github.com/tapjs/signal-exit/blob/395ccc8cf3cc119dc98a0d38940dbfaa590af0cd/signals.js#L24), yet is unsupported in Windows. To wit:

```
$ node
> process.version
'v10.15.3'
> process.kill(process.pid, 'SIGHUP')
{ Error: kill ENOSYS
    at process.kill (internal/process/per_thread.js:198:13) errno: 'ENOSYS', code: 'ENOSYS', syscall: 'kill' }
```

Perhaps if `SIGHUP` is triggered in this module when on Windows, then it should be replaced by `SIGINT` instead.

**Comment by TooTallNate** [comment]
Ok I was actually able to reproduce this. If running a node script in `cmd.exe` Command Prompt, and then I hit the X to close the terminal window, then this happens (supporting my `SIGHUP` theory).

**Comment by bcoe** [comment]
@TooTallNate please try `+ signal-exit@3.0.3`.
