### ISSUE TITLE
Cannot kill debug client after `onExit()` executed

### ISSUE THREAD

**Issue by wataash** [tapjs/signal-exit#71]
When debugging script with `node --inspect[-*] index.js`, we can exit debug server with Ctrl-C (SIGINT), or kill it with SIGTERM.

```sh
1$ # terminal 1: debug server
1$ cat index.js  # very simple script
console.log("a");

1$ node --inspect-brk index.js

2$ # terminal 2: debug client
2$ node inspect --port=9229
connecting to 127.0.0.1:9229 ... ok
Break on start in index.js:1
> 1 console.log("a");
  2 
debug> 

# terminal1
Debugger attached.
^C
1$ # killed with Ctrl-C
```

But once `onExit()` is executed, we can't kill the server anymore.

```sh
1$ cat index.js
const onExit = require("signal-exit");
onExit(() => {});
console.log("a");

1$ node --inspect-brk index.js

2$ node inspect --port=9229
connecting to 127.0.0.1:9229 ... ok
Break on start in index.js:1
> 1 const onExit = require("signal-exit");
  2 onExit(() => {});
  3 console.log("a");
debug> n
break in index.js:2
  1 const onExit = require("signal-exit");
> 2 onExit(() => {});
  3 console.log("a");
  4 
debug> n
break in index.js:3
  1 const onExit = require("signal-exit");
  2 onExit(() => {});
> 3 console.log("a");
  4 
debug> 

# now we can't kill the server!

# terminal1
Debugger attached.
^C^C^C^C^C
```

This is inconvenient when debugging scripts with the inspect-debug mode in an IDE (such like Visual Studio Code or WebStorm).

Is this an expected behavior?

Tested environment:

- Ubuntu 20.04 amd64
- Linux kernel 5.15.39+
- Node.js v16.18.1

**Comment by wataash** [comment]
I understand that the user-registered signal handlers are invoked only in the event loop, not in a debugger-break. So this issue can't be avoided, right?

**Comment by isaacs** [comment]
Yeah, I think you'd have to tell the debugger to just let it run.  I'll try to see if there's a way to fix it for version 4.

**Comment by isaacs** [comment]
What version of Node are you using?  This works for me in node v18.  I think working around it for earlier node versions is probably not ideal, since any workaround would be challenging and likely to break in v18 anyway.
