### ISSUE TITLE
kExitEmitter Symbol conflict

### ISSUE THREAD

**Issue by elrrrrrrr** [tapjs/signal-exit#76]
~~kExitEmitter points to the same `Symbol.for('signal-exit emitter')` which will output a console.error when use 3.x & 4.x together.
Have you considered replacing the Symbol name, such as Symbol.for('singal-exit emitter v4') ?~~

In the 4.x version, when multiple instances of kEximitEmitter running, it will console.err the message, with the same globalThis. Whether to consider turning off the error log display ?

Since we do not directly depend on `signal-exit` in our project, we are unable to make direct modifications. 

We hope to receive your reply as soon as possible. 🤙

![image](https://user-images.githubusercontent.com/5574625/236609165-1d6ad42d-da59-4db7-ae3a-2860e1283b41.png)

**Comment by isaacs** [comment]
Closed by #77 

Turns out past me was smart and already did the thing to work around signal-exit v3 being in the process :)

**Comment by isaacs** [comment]
If you are seeing this, running `npm update signal-exit` should fix the problem.
